/*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_kb_magicfile_MagicFile */

#ifndef _Included_nl_kb_magicfile_MagicFile
#define _Included_nl_kb_magicfile_MagicFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_kb_magicfile_MagicFile
 * Method:    checkText
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nl_kb_magicfile_MagicFile_checkText
  (JNIEnv *, jclass, jstring);

/*
 * Class:     nl_kb_magicfile_MagicFile
 * Method:    checkMime
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nl_kb_magicfile_MagicFile_checkMime
  (JNIEnv *, jclass, jstring);

/*
 * Class:     nl_kb_magicfile_MagicFile
 * Method:    checkEncoding
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nl_kb_magicfile_MagicFile_checkEncoding
  (JNIEnv *, jclass, jstring);

/*
 * Class:     nl_kb_magicfile_MagicFile
 * Method:    checkTextStream
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nl_kb_magicfile_MagicFile_checkTextStream
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     nl_kb_magicfile_MagicFile
 * Method:    checkMimeStream
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nl_kb_magicfile_MagicFile_checkMimeStream
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     nl_kb_magicfile_MagicFile
 * Method:    checkEncodingStream
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nl_kb_magicfile_MagicFile_checkEncodingStream
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
